<?php
return [
    // Drugs
    [
        'name' => 'Ambrosia Dust',
        'description' => 'Fine golden powder said to grant temporary invulnerability and clarity of mind. Favored by the gods of Olympus.',
        'price' => 12000,
        'stock' => 50,
        'category' => 'Drugs',
        'image_url' => null,
    ],
    [
        'name' => 'Elixir of Perun',
        'description' => 'Brewed from herbs gathered on stormy nights; grants strength and resilience like the Slavic thunder god.',
        'price' => 9500,
        'stock' => 40,
        'category' => 'Drugs',
        'image_url' => null,
    ],
    [
        'name' => 'Petals of Yomi',
        'description' => 'Extracted from flowers in the Japanese underworld, causes lucid dreams and spirit communication.',
        'price' => 8200,
        'stock' => 30,
        'category' => 'Drugs',
        'image_url' => null,
    ],
    [
        'name' => 'Soma Resin',
        'description' => 'Sticky resin used in sacred rites, derived from ancient Vedic-Japanese fusion rituals. Heightens perception and combat focus.',
        'price' => 10000,
        'stock' => 35,
        'category' => 'Drugs',
        'image_url' => null,
    ],
    [
        'name' => 'Bloodwine of Dionysus',
        'description' => 'Forbidden vintage infused with frenzy and ecstasy; not for the faint of heart.',
        'price' => 13800,
        'stock' => 20,
        'category' => 'Drugs',
        'image_url' => null,
    ],

    // Artifacts
    [
        'name' => 'Horn of the Centaur',
        'description' => 'Ancient relic said to control lesser beasts and inspire fear in human hearts.',
        'price' => 18000,
        'stock' => 15,
        'category' => 'Artifacts',
        'image_url' => null,
    ],
    [
        'name' => 'Mirror of Baba Yaga',
        'description' => 'A cracked obsidian mirror that reveals someone’s worst fear or hidden truth.',
        'price' => 16500,
        'stock' => 10,
        'category' => 'Artifacts',
        'image_url' => null,
    ],
    [
        'name' => 'Kagutsuchi’s Emberstone',
        'description' => 'Glowing ember said to be a fragment of the Japanese god of fire; used in deadly incantations.',
        'price' => 20000,
        'stock' => 12,
        'category' => 'Artifacts',
        'image_url' => null,
    ],
    [
        'name' => 'Oracle Coin of Delphi',
        'description' => 'Flip the coin to ask fate a question. Once per day, it answers in cryptic verse.',
        'price' => 15000,
        'stock' => 20,
        'category' => 'Artifacts',
        'image_url' => null,
    ],
    [
        'name' => 'Koschei’s Bone Ring',
        'description' => 'Grants longevity and resistance to physical decay—at a terrible spiritual cost.',
        'price' => 22000,
        'stock' => 8,
        'category' => 'Artifacts',
        'image_url' => null,
    ],

    // Weapons
    [
        'name' => 'Poseidon’s Trident Replica',
        'description' => 'Forged with oceanic steel; controls currents and summons small tidal waves.',
        'price' => 25000,
        'stock' => 6,
        'category' => 'Weapons',
        'image_url' => null,
    ],
    [
        'name' => 'Svarog’s Forge Hammer',
        'description' => 'Crafted in honor of the Slavic god of fire and smithing; deals fire damage with every blow.',
        'price' => 28500,
        'stock' => 5,
        'category' => 'Weapons',
        'image_url' => null,
    ],
    [
        'name' => 'Katana of Susanoo',
        'description' => 'Blade imbued with storm energy; strikes cause thunderclaps and disorientation.',
        'price' => 30000,
        'stock' => 4,
        'category' => 'Weapons',
        'image_url' => null,
    ],
    [
        'name' => 'Bow of Artemis',
        'description' => 'Fires spectral arrows that never miss under the light of the moon.',
        'price' => 26000,
        'stock' => 7,
        'category' => 'Weapons',
        'image_url' => null,
    ],
    [
        'name' => 'Morana’s Ice Dagger',
        'description' => 'Freezes blood on contact; named after the Slavic goddess of death and winter.',
        'price' => 24200,
        'stock' => 10,
        'category' => 'Weapons',
        'image_url' => null,
    ],

    // Services
    [
        'name' => 'Summoning Ritual: Hades',
        'description' => 'Invoke the Greek god of the underworld for forbidden knowledge—at your own peril.',
        'price' => 35000,
        'stock' => 3,
        'category' => 'Services',
        'image_url' => null,
    ],
    [
        'name' => 'Binding Spell: Rusalka Spirit',
        'description' => 'Slavic ritual to trap and control a vengeful female water spirit.',
        'price' => 31000,
        'stock' => 4,
        'category' => 'Services',
        'image_url' => null,
    ],
    [
        'name' => 'Talisman Imbuing Ceremony',
        'description' => 'Shinto-style blessing performed remotely to empower personal artifacts.',
        'price' => 29500,
        'stock' => 5,
        'category' => 'Services',
        'image_url' => null,
    ],
    [
        'name' => 'Olympian Blood Pact',
        'description' => 'Forge a pact with a minor Greek deity in exchange for temporary power.',
        'price' => 40000,
        'stock' => 2,
        'category' => 'Services',
        'image_url' => null,
    ],
    [
        'name' => 'Yokai Consultation & Summoning',
        'description' => 'A ritual to summon and bind a yokai for guidance or revenge.',
        'price' => 38000,
        'stock' => 3,
        'category' => 'Services',
        'image_url' => null,
    ],
];
